name: Check code

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check for lint and typescript error
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - run: npm i
      - run: npm run check
